import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  appShell: {
    flex: 1,
    backgroundColor: '#060A14',
    alignItems: 'center',
  },
  surfaceFrame: {
    flex: 1,
    width: '100%',
    backgroundColor: '#060A14',
  },
  surfaceFrameDesktop: {
    maxWidth: 1920,
  },
  surfaceFrameMobile: {
    maxWidth: 430,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: '#101A2A',
  },
  container: {
    flex: 1,
    backgroundColor: '#060A14',
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#000000',
  },
  loadingText: {
    marginTop: 10,
    color: '#9BB0C9',
    fontSize: 14,
  },
  headerRow: {
    paddingTop: Platform.OS === 'web' ? 14 : 48,
    paddingHorizontal: 20,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#000000',
  },
  menuButton: {
    backgroundColor: '#0E1A2B',
    borderColor: '#1F3A59',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  menuButtonText: {
    color: '#DCEBFF',
    fontSize: 13,
    fontWeight: '700',
  },
  greetingCard: {
    backgroundColor: '#0E1A2B',
    borderColor: '#1F3A59',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  headerLogoCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerLogo: {
    width: 168,
    height: 52,
  },
  viewToggleButton: {
    backgroundColor: '#0E1A2B',
    borderColor: '#2A4163',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
    zIndex: 2,
  },
  greeting: {
    color: '#F2F6FF',
    fontSize: 24,
    fontWeight: '800',
  },
  subtitle: {
    color: '#8AA1BF',
    fontSize: 13,
    marginTop: 2,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 120,
    paddingTop: 16,
  },
  warningBanner: {
    backgroundColor: '#4A1F2A',
    borderColor: '#C7546C',
    borderWidth: 1,
    borderRadius: 4,
    padding: 12,
    marginBottom: 12,
  },
  warningBannerTitle: {
    color: '#FFE3EA',
    fontSize: 13,
    fontWeight: '800',
  },
  warningBannerText: {
    color: '#FFD4DE',
    fontSize: 12,
    marginTop: 4,
  },
  cardStrong: {
    backgroundColor: '#0E1726',
    borderColor: '#263C5D',
    borderWidth: 1,
    borderRadius: 4,
    padding: 18,
    marginBottom: 18,
  },
  cardStrongLabel: {
    color: '#95ABCB',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  cardStrongValue: {
    marginTop: 8,
    color: '#B5FFDD',
    fontSize: 32,
    fontWeight: '800',
  },
  summaryRow: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  summaryText: {
    color: '#8EA4C3',
    fontSize: 12,
    marginTop: 4,
  },
  accountOverviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 18,
  },
  accountOverviewCard: {
    width: '48%',
    backgroundColor: '#101A2A',
    borderColor: '#263E5F',
    borderWidth: 1,
    borderRadius: 4,
    padding: 14,
  },
  accountOverviewCardActive: {
    borderColor: '#53E3A6',
  },
  accountOverviewName: {
    color: '#DCE9FF',
    fontSize: 14,
    fontWeight: '700',
  },
  accountOverviewValue: {
    color: '#EAFBF3',
    fontSize: 22,
    fontWeight: '800',
    marginTop: 8,
  },
  accountOverviewMeta: {
    color: '#8EA4C3',
    fontSize: 12,
    marginTop: 4,
  },
  accountOverviewMetaIncome: {
    color: '#4ade80',
    fontSize: 12,
    marginTop: 4,
  },
  accountOverviewMetaExpense: {
    color: '#f87171',
    fontSize: 12,
    marginTop: 4,
  },
  iconSearchInput: {
    backgroundColor: '#0E1A2B',
    borderColor: '#1F3A59',
    borderWidth: 1,
    borderRadius: 4,
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: '#EAF3FF',
    fontSize: 14,
  },
  sidebarTxRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#1A2E45',
  },
  sidebarTxNote: {
    color: '#C5D9F3',
    fontSize: 13,
    flex: 1,
    marginRight: 8,
  },
  sidebarTxAmount: {
    fontSize: 13,
    fontWeight: '600',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 4,
  },
  sectionTitle: {
    color: '#E5EEFF',
    fontSize: 18,
    fontWeight: '700',
  },
  linkAction: {
    color: '#6ED8A5',
    fontSize: 14,
    fontWeight: '700',
  },
  emptyText: {
    color: '#7389A6',
    marginBottom: 14,
    fontSize: 13,
  },
  chipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 18,
  },
  categoryChip: {
    backgroundColor: '#121D2E',
    borderWidth: 1,
    borderColor: '#273A58',
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  categoryChipText: {
    color: '#D8E6FF',
    fontSize: 13,
    fontWeight: '600',
  },
  categoryChipType: {
    color: '#FCA5A5',
    fontSize: 11,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  incomeType: {
    color: '#6ED8A5',
  },
  listCard: {
    backgroundColor: '#101A2A',
    borderColor: '#263E5F',
    borderWidth: 1,
    borderRadius: 4,
    padding: 14,
    marginBottom: 18,
  },
  spendRow: {
    marginBottom: 10,
  },
  spendLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  spendName: {
    color: '#DCE9FF',
    fontSize: 13,
    fontWeight: '600',
  },
  spendAmount: {
    color: '#9DB4D4',
    fontSize: 12,
  },
  spendBarTrack: {
    height: 8,
    backgroundColor: '#1E2F49',
    borderRadius: 999,
    overflow: 'hidden',
  },
  spendBarFill: {
    height: '100%',
    backgroundColor: '#FB7185',
    borderRadius: 999,
  },
  transactionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomColor: '#1D2F47',
    borderBottomWidth: 1,
    paddingVertical: 10,
    gap: 12,
  },
  transactionTitle: {
    color: '#F0F6FF',
    fontWeight: '600',
    fontSize: 14,
  },
  transactionMeta: {
    color: '#7891B1',
    fontSize: 12,
    marginTop: 2,
  },
  transactionAmount: {
    fontWeight: '700',
    fontSize: 14,
  },
  positive: {
    color: '#4ade80',
  },
  negative: {
    color: '#f87171',
  },
  pendingCard: {
    backgroundColor: '#121C2B',
    borderColor: '#35547D',
    borderWidth: 1,
    borderRadius: 4,
    padding: 14,
    marginBottom: 18,
  },
  pendingTitle: {
    color: '#DCE9FF',
    fontWeight: '700',
    marginBottom: 10,
  },
  pendingAccountName: {
    color: '#E9F1FF',
    fontWeight: '700',
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    backgroundColor: '#08111D',
    borderTopWidth: 1,
    borderTopColor: '#20334F',
  },
  bottomBarIncome: {
    flex: 1,
    backgroundColor: '#166534',
    paddingVertical: 14,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomBarTransfer: {
    flex: 1,
    backgroundColor: '#214264',
    paddingVertical: 14,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomBarExpense: {
    flex: 1,
    backgroundColor: '#9f1239',
    paddingVertical: 14,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomBarIcon: {
    color: '#EAF2FF',
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.44)',
    justifyContent: 'flex-start',
  },
  menuOverlayTapArea: {
    ...StyleSheet.absoluteFillObject,
  },
  menuPanel: {
    position: 'absolute',
    left: 0,
    marginTop: 48,
    width: 360,
    maxWidth: '92%',
    maxHeight: '86%',
    backgroundColor: '#0D1625',
    borderColor: '#2A4163',
    borderWidth: 1,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    padding: 16,
    gap: 8,
  },
  menuTitle: {
    color: '#F0F7FF',
    fontWeight: '800',
    fontSize: 18,
    marginBottom: 8,
  },
  menuScrollContent: {
    paddingBottom: 12,
    gap: 8,
  },
  menuSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  menuSectionTitle: {
    color: '#8FA8C9',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  menuIconAction: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#173129',
    borderColor: '#2B5A4B',
    borderWidth: 1,
  },
  menuIconActionText: {
    color: '#B5FFDD',
    fontSize: 16,
    fontWeight: '800',
  },
  menuChipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  menuChip: {
    backgroundColor: '#16283D',
    borderColor: '#2D486E',
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 10,
  },
  menuChipActive: {
    borderColor: '#53E3A6',
    backgroundColor: '#1D3A3C',
  },
  menuChipText: {
    color: '#EAF3FF',
    fontSize: 12,
    fontWeight: '700',
  },
  menuChipGhost: {
    borderColor: '#37557F',
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 10,
  },
  menuChipGhostText: {
    color: '#6EC7FF',
    fontSize: 12,
    fontWeight: '700',
  },
  customRangeStack: {
    marginBottom: 8,
  },
  manageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#142235',
    borderColor: '#1E3552',
    borderWidth: 1,
    borderRadius: 4,
    padding: 10,
  },
  managePrimary: {
    flex: 1,
  },
  manageTitle: {
    color: '#EAF3FF',
    fontSize: 13,
    fontWeight: '700',
  },
  manageMeta: {
    color: '#8FA8C9',
    fontSize: 11,
    marginTop: 3,
  },
  manageIconButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1D304A',
  },
  manageIconButtonDanger: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5F2434',
  },
  manageIconText: {
    color: '#EAF3FF',
    fontSize: 14,
    fontWeight: '800',
  },
  managePill: {
    color: '#A6BCD9',
    fontSize: 11,
    fontWeight: '700',
    backgroundColor: '#1D304A',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  manageNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  managePrimaryBadge: {
    color: '#53E3A6',
    fontSize: 12,
    fontWeight: '800',
  },
  manageSmallButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1D304A',
  },
  manageSmallButtonDisabled: {
    opacity: 0.25,
  },
  manageSmallButtonActive: {
    backgroundColor: '#1A3D2E',
  },
  manageSmallText: {
    color: '#EAF3FF',
    fontSize: 12,
    fontWeight: '800',
  },
  manageSmallTextActive: {
    color: '#53E3A6',
  },
  menuItem: {
    backgroundColor: '#142235',
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuItemText: {
    color: '#D7E6FC',
    fontWeight: '600',
  },
  menuDanger: {
    marginTop: 6,
    backgroundColor: '#5F2434',
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuDangerText: {
    color: '#FFE3E9',
    fontWeight: '700',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    padding: 16,
  },
  modalCard: {
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    backgroundColor: '#0F1A2B',
    borderColor: '#2A3F60',
    borderWidth: 1,
    borderRadius: 4,
    padding: 16,
    maxHeight: '94%',
  },
  entryModalCard: {
    maxWidth: 560,
    minHeight: '84%',
  },
  modalTitle: {
    color: '#F1F6FF',
    fontWeight: '800',
    fontSize: 18,
    marginBottom: 10,
  },
  modalLabel: {
    color: '#A3B9D8',
    marginBottom: 6,
    marginTop: 6,
    fontSize: 12,
  },
  modalMeta: {
    color: '#8FA8C9',
    marginBottom: 10,
    fontSize: 12,
  },
  input: {
    backgroundColor: '#111F32',
    borderColor: '#2E496F',
    borderWidth: 1,
    borderRadius: 4,
    color: '#EDF5FF',
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  entryTopRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  entryDateInput: {
    flex: 1,
  },
  entryAccountBtn: {
    backgroundColor: '#16283D',
    borderColor: '#2D486E',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  entryAccountBtnText: {
    color: '#EAF3FF',
    fontWeight: '700',
    fontSize: 12,
  },
  entryAccountBtnFull: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 8,
  },
  entryTypeRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  toggleButton: {
    flex: 1,
    backgroundColor: '#13253B',
    borderWidth: 1,
    borderColor: '#2C4669',
    borderRadius: 4,
    alignItems: 'center',
    paddingVertical: 9,
  },
  toggleButtonActive: {
    borderColor: '#53E3A6',
    backgroundColor: '#1D3A3C',
  },
  toggleButtonActiveIncome: {
    borderColor: '#4ade80',
    backgroundColor: '#0f2a1a',
  },
  toggleButtonActiveExpense: {
    borderColor: '#f87171',
    backgroundColor: '#2a0f0f',
  },
  toggleButtonText: {
    color: '#EAF1FF',
    fontWeight: '700',
  },
  toggleButtonTextIncome: {
    color: '#4ade80',
    fontWeight: '700',
  },
  toggleButtonTextExpense: {
    color: '#f87171',
    fontWeight: '700',
  },
  entryAmountInput: {
    backgroundColor: '#091426',
    borderColor: '#35527A',
    borderWidth: 1,
    borderRadius: 4,
    color: '#F1F6FF',
    fontSize: 34,
    fontWeight: '800',
    textAlign: 'center',
    paddingVertical: 8,
    marginBottom: 4,
  },
  entryCurrencyText: {
    textAlign: 'center',
    color: '#8FA8C9',
    marginBottom: 8,
  },
  modalChipsRow: {
    gap: 8,
    paddingBottom: 10,
  },
  modalChip: {
    backgroundColor: '#16283D',
    borderColor: '#2D486E',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 7,
    paddingHorizontal: 10,
  },
  modalChipActive: {
    borderColor: '#53E3A6',
  },
  modalChipText: {
    color: '#EAF3FF',
    fontSize: 12,
    fontWeight: '600',
  },
  numpadGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  numpadKey: {
    width: '31%',
    backgroundColor: '#142235',
    borderColor: '#2D486E',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 12,
    alignItems: 'center',
  },
  numpadKeyText: {
    color: '#EAF3FF',
    fontSize: 20,
    fontWeight: '700',
  },
  tagCreateRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  tagInput: {
    flex: 1,
    marginBottom: 0,
  },
  smallAction: {
    backgroundColor: '#1B2A41',
    borderColor: '#37557F',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  smallActionText: {
    color: '#D8E8FF',
    fontSize: 12,
    fontWeight: '700',
  },
  currencyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  currencyOption: {
    backgroundColor: '#16283D',
    borderColor: '#2D486E',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  currencyOptionActive: {
    borderColor: '#53E3A6',
    backgroundColor: '#1D3A3C',
  },
  currencyOptionText: {
    color: '#EAF3FF',
    fontSize: 12,
    fontWeight: '700',
  },
  toggleRowCompact: {
    flexDirection: 'row',
    gap: 8,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 8,
  },
  modalSecondary: {
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#3A5378',
    paddingHorizontal: 14,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSecondaryText: {
    color: '#BAD0EE',
    fontWeight: '700',
  },
  modalPrimary: {
    borderRadius: 4,
    backgroundColor: '#53E3A6',
    paddingHorizontal: 14,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalPrimaryText: {
    color: '#082215',
    fontWeight: '800',
  },
  modalDanger: {
    borderRadius: 4,
    backgroundColor: '#5F2434',
    paddingHorizontal: 14,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalDangerText: {
    color: '#FFE3E9',
    fontWeight: '800',
  },
  // Desktop two-column layout
  desktopTwoColRow: {
    flexDirection: 'row',
    gap: 18,
    alignItems: 'flex-start',
  },
  desktopColLeft: {
    flex: 1,
  },
  desktopColRight: {
    flex: 1,
  },
  // Desktop body wrapper (main scroll + sidebar)
  desktopBodyWrapper: {
    flex: 1,
    flexDirection: 'row',
  },
  desktopSidebar: {
    width: '30%' as any,
    minWidth: 280,
    maxWidth: 480,
    borderLeftWidth: 1,
    borderLeftColor: '#1A2E45',
  },
  desktopSidebarContent: {
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 80,
  },
  // Spend row category active highlight
  spendRowActive: {
    backgroundColor: '#15293D',
    borderRadius: 4,
    marginHorizontal: -4,
    paddingHorizontal: 4,
  },
  spendNameActive: {
    color: '#53E3A6',
  },
  spendBarFillActive: {
    backgroundColor: '#53E3A6',
  },
  // Filtered transactions header
  filterLabelRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  filterLabelSub: {
    color: '#7391B0',
    fontSize: 13,
  },
  sectionHeaderActions: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  // Avatar button
  avatarBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#1F3A59',
    zIndex: 2,
  },
  avatarImg: {
    width: '100%',
    height: '100%',
  },
  avatarFallback: {
    width: '100%',
    height: '100%',
    backgroundColor: '#0E1A2B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallbackText: {
    color: '#F2F6FF',
    fontSize: 18,
    fontWeight: '800',
  },
  // Collapsible card header
  cardCollapseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardCollapseHeaderRight: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  collapseChevron: {
    color: '#6ED8A5',
    fontSize: 16,
    fontWeight: '700',
    paddingHorizontal: 4,
  },
  // Interval pill
  intervalPillRow: {
    flexDirection: 'row',
    marginTop: 8,
    marginBottom: 2,
  },
  intervalPill: {
    backgroundColor: '#16283D',
    borderColor: '#2D486E',
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 12,
  },
  intervalPillText: {
    color: '#EAF3FF',
    fontSize: 12,
    fontWeight: '700',
  },
  intervalPickerWrap: {
    marginTop: 8,
    marginBottom: 4,
  },
  // Section header left cluster
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  collapseTrigger: {
    paddingHorizontal: 2,
  },
  // Battery chart
  batteryWrap: {
    marginBottom: 18,
  },
  batteryTrack: {
    flexDirection: 'row',
    height: 36,
    borderRadius: 4,
    overflow: 'hidden',
    backgroundColor: '#1E2F49',
  },
  batterySegmentSpent: {
    backgroundColor: '#f87171',
    alignItems: 'center',
    justifyContent: 'center',
  },
  batterySegmentTransfer: {
    backgroundColor: '#a855f7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  batterySegmentUnspent: {
    backgroundColor: '#1D5A40',
    alignItems: 'center',
    justifyContent: 'center',
  },
  batterySegLabel: {
    color: '#F0FFF8',
    fontSize: 12,
    fontWeight: '700',
  },
  batteryLegend: {
    flexDirection: 'row',
    gap: 20,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  batteryLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  batteryLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  batteryLegendText: {
    color: '#8EA4C3',
    fontSize: 12,
  },
  // Account picker in entry modal
  entryAccountBtnActive: {
    borderColor: '#53E3A6',
    backgroundColor: '#1D3A3C',
  },
  // Bottom bar disabled state
  bottomBarDisabled: {
    opacity: 0.3,
  },
  // Category chip inner row
  categoryChipInner: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  // Mobile category picker
  mobileCategoryPill: {
    backgroundColor: '#111F32',
    borderColor: '#2E496F',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  mobileCategoryPillOpen: {
    borderColor: '#53E3A6',
    backgroundColor: '#0F2A1E',
  },
  mobileCategoryPillText: {
    color: '#EDF5FF',
    fontWeight: '600',
    fontSize: 14,
  },
  mobileCategoryPickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  mobileCategoryPickerItem: {
    backgroundColor: '#16283D',
    borderColor: '#2D486E',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignItems: 'center',
    gap: 4,
    minWidth: 72,
  },
  mobileCategoryPickerItemActive: {
    borderColor: '#53E3A6',
    backgroundColor: '#1D3A3C',
  },
  mobileCategoryPickerText: {
    color: '#D8E6FF',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  // Icon picker
  iconPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  iconPickerPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#16283D',
    borderColor: '#2D486E',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  iconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingVertical: 4,
  },
  iconGridItem: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#16283D',
    borderColor: '#2D486E',
    borderWidth: 1,
    borderRadius: 4,
  },
  iconGridItemActive: {
    borderColor: '#53E3A6',
    backgroundColor: '#1D3A3C',
  },
  // Color presets
  colorPresetRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 10,
  },
  colorPresetDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorPresetDotActive: {
    borderColor: '#FFFFFF',
    transform: [{ scale: 1.15 }],
  },
  // Scroll-to-top FAB
  scrollTopFab: {
    position: 'absolute',
    right: 100,
    bottom: 130,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#53E3A6',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  // Transfer amount colour
  transferAmount: {
    color: '#60A5FA',
  },
  // Date pressable row
  datePressable: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#111F32',
    borderColor: '#2E496F',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  datePressableText: {
    flex: 1,
    color: '#EDF5FF',
    fontSize: 14,
  },
  // Entry modal – full-screen mobile
  entryModalFullscreen: {
    flex: 1,
    backgroundColor: '#060A14',
  },
  entryModalTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'web' ? 16 : 52,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#1A2B40',
  },
  entryModalCloseBtn: {
    padding: 4,
  },
  entryModalTitle: {
    color: '#F0F7FF',
    fontWeight: '800',
    fontSize: 16,
  },
  entryModalScrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    paddingTop: 8,
  },
  // Amount display-only
  entryAmountDisplay: {
    backgroundColor: '#091426',
    borderColor: '#35527A',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 10,
    marginBottom: 4,
    alignItems: 'center',
  },
  entryAmountDisplayText: {
    color: '#F1F6FF',
    fontSize: 40,
    fontWeight: '800',
    letterSpacing: 1,
  },
  // Bottom bar (mobile entry modal)
  chooseCategoryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#53E3A6',
    margin: 16,
    paddingVertical: 16,
    borderRadius: 8,
  },
  chooseCategoryBtnText: {
    color: '#060A14',
    fontSize: 17,
    fontWeight: '800',
  },
  entryModalBottomBar: {
    borderTopWidth: 1,
    borderTopColor: '#1A2B40',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'web' ? 16 : 28,
    gap: 8,
  },
  categoryIndicatorBtn: {
    backgroundColor: '#111F32',
    borderColor: '#2A4060',
    borderWidth: 1,
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  categoryIndicatorText: {
    color: '#EDF5FF',
    fontWeight: '600',
    fontSize: 14,
  },
  entryModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  // Date Picker modal
  datePickerCard: {
    width: 320,
    maxWidth: '95%',
  },
  dpMonthNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  dpNavBtn: {
    padding: 8,
  },
  dpNavBtnText: {
    color: '#53E3A6',
    fontSize: 22,
    fontWeight: '700',
  },
  dpMonthTitle: {
    color: '#EAF3FF',
    fontWeight: '700',
    fontSize: 15,
  },
  dpWeekRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  dpWeekDay: {
    flex: 1,
    textAlign: 'center',
    color: '#8FA8C9',
    fontSize: 11,
    fontWeight: '700',
  },
  dpDayGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  dpDayCell: {
    width: `${100 / 7}%` as any,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dpDayCellSelected: {
    backgroundColor: '#53E3A6',
    borderRadius: 99,
  },
  dpDayCellToday: {
    borderWidth: 1,
    borderColor: '#53E3A6',
    borderRadius: 99,
  },
  dpDayText: {
    color: '#D8E6FF',
    fontSize: 14,
  },
  dpDayTextSelected: {
    color: '#060A14',
    fontWeight: '800',
  },
  // Fullscreen category picker
  catPickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'web' ? 20 : 56,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1A2B40',
  },
  catPickerTitle: {
    color: '#F0F7FF',
    fontWeight: '800',
    fontSize: 20,
  },
  catPickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 12,
    gap: 10,
  },
  catPickerItem: {
    width: '30%',
    minWidth: 96,
    backgroundColor: '#101E30',
    borderColor: '#263E5F',
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 16,
    paddingHorizontal: 8,
    alignItems: 'center',
    gap: 8,
  },
  catPickerItemActive: {
    borderColor: '#53E3A6',
    backgroundColor: '#1D3A3C',
  },
  catPickerItemText: {
    color: '#D8E6FF',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  catPickerItemType: {
    color: '#FCA5A5',
    fontSize: 10,
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  catPickerItemSub: {
    color: '#8FA8C9',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 2,
  },
});
